/* ============================================================
   术语速查表（Glossary）
   黑话 → 一句话解释 → 出处课程
   ============================================================ */
window.GLOSSARY = [
  { term: "Harness", en: "harness", explain: "英文原意「马具/线束」。DeepSeek Harness = 把模型、工具、记忆、插件、权限「总装」起来的智能体调度台。", src: "s1-1" },
  { term: "智能体", en: "agent", explain: "不仅能聊天、还能自己决定下一步并动手做事的 AI（会调用工具、执行命令）。", src: "s1-1" },
  { term: "工具", en: "tool", explain: "给模型用的「手」：终端命令、文件读写、网页搜索等，由 dsh-tool-* 插件提供。", src: "s4-1" },
  { term: "插件", en: "plugin", explain: "按需安装的「能力包」，装进 Harness 后给它增加一种新能力。", src: "s1-2" },
  { term: "Bundle", en: "bundle", explain: "一组插件组成的安装清单/入口；装一个 bundle = 一次声明多个插件。", src: "s1-3" },
  { term: "Profile", en: "profile", explain: "一套独立的 Harness 运行配置（如 web 档案、headless 档案），互不干扰。", src: "s1-3" },
  { term: "ESM", en: "ECMAScript Modules", explain: "JavaScript 官方模块标准：用 import 拿进来、export 交出去。", src: "s2-1" },
  { term: ".mjs", en: "module javascript", explain: "明确声明「这是 ESM 文件」的后缀；或在 package.json 写 \"type\": \"module\"。", src: "s2-1" },
  { term: "Node.js", en: "Node.js", explain: "能在电脑上直接运行 JavaScript 的程序；DSH 整个建在它之上。", src: "s2-1" },
  { term: "npm / pnpm", en: "package managers", explain: "包管理器：负责下载、安装、卸载 npm 世界的代码包。DSH 内部用 pnpm。", src: "s1-2" },
  { term: "YAML", en: "YAML", explain: "给人类看的配置格式：缩进表示层级、- 表示列表、# 表示注释。", src: "s2-2" },
  { term: "Cordis", en: "Cordis", explain: "DSH 使用的插件框架（与 Koishi 同源），所有 DSH 插件都是 Cordis 插件。", src: "s2-3" },
  { term: "Context", en: "context", explain: "插件的「上下文/工位」：生命周期、服务、事件都挂在它上面。", src: "s2-3" },
  { term: "Service", en: "service", explain: "插件间互相借用的「公用设施」：用 ctx.get 拿、ctx.provide 给、inject 声明依赖。", src: "s2-3" },
  { term: "inject", en: "inject", explain: "插件导出的依赖声明：告诉 DSH「启动我之前先准备好这些服务」。", src: "s2-3" },
  { term: "Schema", en: "schema", explain: "配置声明：声明插件接受哪些配置、类型和默认值（schemastery 库）。", src: "s2-3" },
  { term: "事件", en: "event", explain: "Harness 运行时发出的「办公室广播」，插件用 ctx.on 订阅（如 agent/session-start）。", src: "s2-3" },
  { term: "apply(ctx)", en: "apply", explain: "每个插件的入口函数；DSH 启动时调用它，ctx 是插件获得的上下文。", src: "s2-3" },
  { term: "ctx.effect", en: "effect", explain: "注册「要长期活着的事」，返回的清理函数在插件停用时执行——资源管理铁律。", src: "s2-3" },
  { term: "cordis.yml", en: "cordis config", explain: "DSH 启动时按 bundle 清单 + patch 生成的「最终组装配置」。", src: "s1-4" },
  { term: "cordis.patch.yml", en: "bundle patch", explain: "bundle 插件带的「补丁」：声明往组合里 insert 哪些插件实例。", src: "s2-4" },
  { term: "dsh.bundle.patch", en: "bundle patch field", explain: "package.json 里的身份字段：指向 cordis.patch.yml，证明「我是 bundle 插件」。", src: "s2-4" },
  { term: "Node half", en: "node side", explain: "插件的服务端部分（lib/index.mjs）：挂路由、开服务、监听事件。", src: "s2-4" },
  { term: "client half", en: "client side", explain: "插件的浏览器部分：通过 __ModuleLoader__ 挂载进网页，用 fetch 调 Node half。", src: "s2-4" },
  { term: "webServer", en: "web server service", explain: "DSH 提供的网页服务器服务：插件用它挂 HTTP 路由（register exact/prefix）。", src: "practice/error-logger/logic" },
  { term: "route / handler", en: "route", explain: "路由 = 「访问哪个路径执行哪段函数」的登记；handler 就是那段函数(req, res)。", src: "practice/error-logger/logic" },
  { term: "schemastery", en: "schemastery", explain: "DSH 的配置声明库：Schema.boolean() / Schema.number() 等，校验并套默认值。", src: "practice/error-logger/config" },
  { term: "settings.yaml", en: "settings file", explain: "用户设置文件（~/.dsh/settings.yaml）：插件配置写这里，支持热更新。", src: "practice/error-logger/config" },
  { term: "热更新", en: "live config", explain: "改 settings.yaml 不用重启即生效：注册配置时用 applies: \"live\" + watch。", src: "practice/error-logger/config" },
  { term: "dump-config", en: "dump config", explain: "dsh 命令：只打印组装配置、不启动服务，用来验证插件有没有进树。", src: "s1-4" },
  { term: "EADDRINUSE", en: "address in use", explain: "端口被占用（上个实例没关干净）的经典报错；netstat 找 PID 再 taskkill。", src: "s2-5" },
  { term: "沙箱", en: "sandbox", explain: "工具执行的隔离环境：限权、隔离，配合审批机制防止 AI 乱来。", src: "s4-1" },
  { term: "子代理", en: "subagent", explain: "主代理派出的「分身」：独立上下文并行干活，做完交回结果。", src: "s4-2" },
  { term: "/goal", en: "goal command", explain: "目标驱动循环：AI 反复推进直到完成或卡住。适合「结果明确、过程随意」的任务。", src: "s4-2" },
  { term: "/plan", en: "plan mode", explain: "计划模式：AI 先出计划给你批准，再动手执行。适合大改动。", src: "s4-2" },
  { term: "MCP", en: "Model Context Protocol", explain: "模型上下文协议：外部能力的「USB-C 统一插座」，接上就能用。", src: "s4-3" },
  { term: "Skill", en: "skill", explain: "打包好的「手艺教材」：领域说明 + 步骤 + 示例，让模型现学现用。", src: "s4-3" },
  { term: "__ModuleLoader__", en: "client module loader", explain: "DSH 网页端的模块挂载通道：client half 通过它进入页面。", src: "s2-4" },
  { term: "monorepo", en: "monorepo", explain: "一个仓库装多个包的结构（deepseek-harness：apps/cli、apps/web、packages/）。", src: "s4-4" },
  { term: "PR", en: "Pull Request", explain: "GitHub 上的「合并请求」：改完代码请求原仓库采纳你的修改。", src: "s4-4" },
]
